### ISSUE TITLE
Source debug

### ISSUE THREAD

**Issue by dbernhard** [englue/meteor-bootstrap3-sass#20]
I can't seem to debug the source sass on my dev machine. Chrome inspector is set up to read source maps but all I'm seeing is the concatenated css file. Is this a known issue?

Thanks,
db

**Comment by reywood** [comment]
Sorry for the delayed response. This project just provides the SCSS files. Sourcemaps would be created by the SCSS compiler which, in this case, is the [fourseven:scss](https://github.com/fourseven/meteor-scss) package. This issue should be brought up there.
