### ISSUE TITLE
Don't forcibly include fourseven:scss

### ISSUE THREAD

**Issue by lassombra** [englue/meteor-bootstrap3-sass#21]
Please allow consumers of your package to choose their own sass implementation (there are multiple out there) and don't use/imply fourseven:scss directly

**Comment by reywood** [comment]
Version 3.3.4_2 no longer installs fourseven:scss.

**Comment by niranjans** [comment]
@reywood I'm not sure if I am missing something. But the new 3.3.5_2 still requires an older version of fourseven:scss. Could you please let me know if this package is still supported?
