### ISSUE TITLE
conflict: constraint fourseven:scss has newer version

### ISSUE THREAD

**Issue by croogie** [englue/meteor-bootstrap3-sass#22]
Output from console:
```
$ meteor add reywood:bootstrap3-sass
 => Errors while adding packages:             
                                              
While selecting package versions:
error: conflict: constraint fourseven:scss@0.9.5 is not satisfied by 2.0.1_5.
Constraints on fourseven:scss come from:
<top level>
reywood:bootstrap3-sass@3.1.5
```

**Comment by Lean41** [comment]
Cannot use your package with new Windows preview version. New version of fourseven:scss, 2.0.1_5 fixes the problem.

meteor update --release WINDOWS-PREVIEW@0.3.0
=> Errors while initializing project:

While checking for fourseven:scss@1.0.0:
error: No compatible build found

**Comment by reywood** [comment]
Updated to use latest version of fourseven:scss. Also updated to bootstrap 3.3.4.
