### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by netm** [englue/meteor-bootstrap3-sass#25]
Hi there, I am new to Meteor (coming from PHP/Laravel world) and I'd be super keen to see/help the documentation for this package include some basics for newbies which get them over the hump:

    * Where do I put my .scss file in my barebones project?
    * How is the parsing of the .scss into .css triggered? 
    * How do I control where the resulting .css ends up?

:-)

**Comment by reywood** [comment]
Where you put your .scss files is up to you. I put mine in `client/stylesheets`. Compilation of .scss files happens automatically any time you make a change. If you have your site open in a web browser, it will update automatically as well when compilation is complete. You have no control over where the compiled .css files end up. The Meteor framework takes care of it for you so you don't have to worry about it.

**Comment by netm** [comment]
Cripes - I get it now, is that sort of goodness even legal?
